/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  safelist: [
    {
      pattern: /grid-(cols|rows)-(1|2|3|4|5|6|7|8|9|10|11|12)/,
    },
  ],
  prefix: '',
  theme: {
    screens: {
      mobile: { min: '300px', max: '767px' },
      tablet: { min: '768px', max: '1279px' },
      desktop: '1280px',
    },
    container: {
      center: true,
      padding: '1.25rem',
      screens: {
        '2xl': '1400px',
      },
    },
    fontWeight: {
      light: '300',
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    fontFamily: {
      'noto-tc': ['Noto Sans TC'],
      'times-new-roman': ['Times New Roman'],
      'roboto-mono': ['Roboto Mono'],
      'roboto-flex': ['Roboto Flex'],
    },
    extend: {
      colors: {
        'default-secondary': '#F5F5F5',
        'text-black': '#1C2024',
        'text-2': '#646464',
        'text-secondary': '#757575',
        'neutral-2': '#F9F9FB',
        'neutral-3': '#F0F0F3',
        'neutral-4': '#E8E8EC',
        'neutral-5': '#E0E1E6',
        'neutral-6': '#D9D9E0',
        'neutral-7': '#CDCED6',
        'neutral-8': '#B9BBC6',
        'neutral-9': '#8B8D98',
        'neutral-10': '#80838D',
        'neutral-11': '#60646C',
        'neutral-12': '#1C2024',

        'accent-1': '#FAFDFE',
        'accent-2': '#F2FAFB',
        'accent-3': '#DEF7F9',
        'accent-4': '#D8F3F6',
        'accent-5': '#C4EAEF',
        'accent-6': '#9DDDE7',
        'accent-7': '#84CDDA',
        'accent-8': '#00A3C0',
        'accent-9': '#00A2C7',
        'accent-10': '#0894B3',
        'accent-11': '#00718DF3',

        'success-1': '#FBFEFC',
        'success-2': '#F4FBF6',
        'success-3': '#E9F7EE',
        'success-4': '#D6F1DF',
        'success-5': '#C4E8D1',
        'success-6': '#ADDDC0',
        'success-7': '#8ECEAA',
        'success-8': '#5BB98B',
        'success-9': '#30A46C',
        'success-10': '#2B9A66',
        'success-11': '#218358',
        'success-12': '#193B2D',

        'error-1': '#FFFCFC',
        'error-2': '#FFF7F7',
        'error-3': '#FEEBEC',
        'error-4': '#FFDBDC',
        'error-5': '#FFCDCE',
        'error-6': '#FDBDBE',
        'error-7': '#F4A9AA',
        'error-8': '#EB8E90',
        'error-9': '#E5484D',
        'error-10': '#DC3E42',
        'error-11': '#CE2C31',
        'error-12': '#641723',

        'warning-1': '#FEFDFB',
        'warning-2': '#FEFBE9',
        'warning-3': '#FFF7C2',
        'warning-4': '#FFEE9C',
        'warning-5': '#FBE577',
        'warning-6': '#F3D673',
        'warning-7': '#E9C162',
        'warning-8': '#E2A336',
        'warning-9': '#FFC53D',
        'warning-10': '#FFBA18',
        'warning-11': '#AB6400',
        'warning-12': '#4F3422',

        'info-3': '#E1F6FD',
        'info-9': '#7CE2FE',
        'info-11': '#00749E',

        'subtitle-gray': '#747474',
        'chatroom-bg': '#F9F9FB',
        'border-bg': '#E8E8EC',
      },
      fontFamily: {
        'times-new-roman': ['"Times New Roman"', 'serif'],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
